places = ["varansi","ujjain","nalanda","rajgir","andaman"]
print(places)
print(sorted(places))
print(places)
print(sorted(places,reverse=True))
print(places)
places.reverse()
print(places)
places.reverse()
print(places)
places.sort()
print(places)
places.sort(reverse=True)
print(places)
print("that's all for now")
print(f"i wnat to visit {places[0].title()}")
places.append("sandha")
print(places)
del places[2]
print(places)
p_rom = places.pop(0)
print(f"i am not visisting {p_rom.title()}")
print(places)
places.insert(1,"chapra")
print(places)
places.remove("chapra")
print(places)
av = "sandha"
places.remove(av)
print(places)
