guest = ["bholu","golu","ganesh","mahesh"]
print(f"{guest[1].title()} nahi aayenge ")
guest_no = guest.pop(1)
guest.append("kunal")
print(f"unke jagah {guest[-1].title()} aayenge")
print(f" baki guest {guest[1].title()},{guest[2].title()},{guest[3].title()} aayenge ")
guest.insert(0,"molu")
guest.insert(3,"sumit")
guest.append("pencil")
print(f"{guest[0]},{guest[3]},{guest[-1]} aath me aayenge")
guest_no = guest.pop(0)
print(f"{guest_no} tum nahi aavoge")
guest_no = guest.pop(0)
print(f"{guest_no} tum bhi nahi aavoge")
guest_no = guest.pop(0)
print(f"{guest_no} tum bhi nahi aavoge")
guest_no = guest.pop(0)
print(f"{guest_no} tum bhi nahi aavoge")
print(guest)
guest_no = guest.pop(0)
print(f"{guest_no} tum bhi nahi aavoge")
guest_no = guest.pop(0)
print(f"{guest_no} tum bhi nahi aavoge")
guest_no = guest.pop(0)
print(f"{guest_no} tum bhi nahi aavoge")
print(f"I am inviting total guest : {len(guest)}")
print("ullo banaya bada maja aaya 🤣🤣")

